version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
  pre_build:
    commands:
      - npm install
  build:
    commands:
  post_build:
    commands:
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages 
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
artifacts:
  files:
    - src/*
    - node_modules/*
